name: Build MCSEasy For Cross-Platform

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: '版本号，例如 v1.2.0.0'
        required: false
        default: 'v0.0.0'
      release_type:
        type: string
        description: '发行类型，例如 Beta, RC1, GA'
        required: false
        default: 'GA'
      suffix:
        type: string
        description: '可选说明后缀，例如 GUIRefactor'
        required: false
        default: ''

jobs:
  build-multi:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10.11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller psutil PyQt5

      - name: Normalize inputs and build artifact tag
        shell: bash
        run: |
          VERSION="${{ github.event.inputs.version || 'v0.0.0' }}"
          RELEASE_TYPE="${{ github.event.inputs.release_type || 'GA' }}"
          SUFFIX="${{ github.event.inputs.suffix || '' }}"
          case "$RELEASE_TYPE" in
            Beta|beta) RELEASE_TYPE='Beta' ;;
            RC|rc|RC1|rc1) RELEASE_TYPE='RC1' ;;
            GA|ga) RELEASE_TYPE='GA' ;;
            *) RELEASE_TYPE='GA' ;;
          esac
          if [ -n "$SUFFIX" ]; then ART_TAG="${VERSION}-${RELEASE_TYPE}-${SUFFIX}"; else ART_TAG="${VERSION}-${RELEASE_TYPE}"; fi
          echo "ARTIFACT_TAG=${ART_TAG}" >> $GITHUB_ENV

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $src = "$env:GITHUB_WORKSPACE\url_list.txt"
          $dist = "$env:GITHUB_WORKSPACE\dist\windows"
          Remove-Item -Recurse -Force $dist -ErrorAction SilentlyContinue
          pyinstaller --clean --noconfirm --log-level=ERROR --onefile --windowed --name=MCSEasy --icon="$env:GITHUB_WORKSPACE\icon.ico" --add-data="$src;." --distpath $dist --workpath "$env:GITHUB_WORKSPACE\build_windows" --specpath "$env:GITHUB_WORKSPACE\build_windows" --optimize=2 --exclude-module tkinter --exclude-module tests gui-re-main.py
          if (Test-Path $dist) { Get-ChildItem -Path $dist | Write-Output }
          echo "ARTIFACT_PATH=dist\\windows" >> $env:GITHUB_ENV

      - name: Build on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          src="$GITHUB_WORKSPACE/url_list.txt"
          dist="$GITHUB_WORKSPACE/dist/macos"
          rm -rf "$dist"
          pyinstaller --clean --noconfirm --log-level=ERROR --onefile --windowed --name=MCSEasy --icon="$GITHUB_WORKSPACE/icon.icns" --add-data "$src:." --distpath "$dist" --workpath "$GITHUB_WORKSPACE/build_macos" --specpath "$GITHUB_WORKSPACE/build_macos" --optimize=2 --strip --exclude-module tkinter --exclude-module tests gui-re-main.py
          ls -la "$dist"
          echo "ARTIFACT_PATH=dist/macos" >> $GITHUB_ENV

      - name: Build on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          src="$GITHUB_WORKSPACE/url_list.txt"
          dist="$GITHUB_WORKSPACE/dist/linux"
          rm -rf "$dist"
          pyinstaller --clean --noconfirm --log-level=ERROR --onefile --name=MCSEasy --icon="$GITHUB_WORKSPACE/icon.png" --add-data "$src:." --distpath "$dist" --workpath "$GITHUB_WORKSPACE/build_linux" --specpath "$GITHUB_WORKSPACE/build_linux" --optimize=2 --strip --exclude-module tkinter --exclude-module tests gui-re-main.py
          ls -la "$dist"
          echo "ARTIFACT_PATH=dist/linux" >> $GITHUB_ENV

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: MCSEasy-${{ env.ARTIFACT_TAG }}-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 7
