name: Build MCSEasy Cross-Platform

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-multi:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10.11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --windowed --name=MCSEasy --icon=icon.ico --add-data "url_list.txt;." --version-file=Version.txt gui-re-main.py

      - name: Build on macOS
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile --windowed --name=MCSEasy --icon=icon.icns --add-data "url_list.txt:." gui-re-main.py

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --name=MCSEasy --icon=icon.png --add-data "url_list.txt:." gui-re-main.py

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: MCSEasy-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/
          retention-days: 7
