name: Build MCSEasy Cross-Platform

on:
 push:
  tags:
   - 'v*'
  branches: [ main ]

jobs:
 build-multi:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest, macos-latest]
    python-version: ['3.10']

  steps:
   - name: Checkout Code
     uses: actions/checkout@v3

   - name: Setup Python
     uses: actions/setup-python@v3
     with:
      python-version: ${{ matrix.python-version }}

   - name: Install Dependencies
     run: |
      python -m pip install --upgrade pip
      pip install pyinstaller

   - name: Determine add-data separator
     run: |
      if [ "$RUNNER_OS" == "Windows" ]; then
       echo "SEPARATOR=;" >> $GITHUB_ENV
      else
       echo "SEPARAOTR=:" >> $GITHUB_ENV
      fi

   - name: Build MCSEasy
     run: |
      if [ "$RUNNER_OS" == "Windows" ]; then
       pyinstaller --onefile --windowed --name=MCSEasy --icon=icon.ico --add-data "url_list.txt${{ env.SEPARATOR }}." --version-file=Version.txt gui-re-main.py
      elif [ "$RUNNER_OS" == "macOS" ]; then
       pyinstaller --onefile --windowed --name=MCSEasy --icon=icon.icns --add-data "url_list.txt${{ env.SEPARATOR }}." gui-re-main.py
      else
       pyinstaller --onefile --name=MCSEasy --icon=icon.png --add-data "url_list.txt${{ env.SEPARATOR }}." gui-re-main.py
      fi
      
   - name: Upload Files
     uses: actions/upload-artifact@v4
     with:
      name: MCSEasy-${{ matrix.os }}-py${{ matrix.python-version }}
      path: |
       dist/
      retention-days: 7
