name: 清理构建工作流

on:
  workflow_dispatch:
    inputs:
      delete_github_artifacts:
        description: '是否删除 GitHub Actions 上的托管'
        required: true
        default: 'false'
        type: boolean
      artifact_prefix:
        description: '被删除托管前缀的文件名'
        required: false
        default: 'MCSEasy'
        type: string

jobs:
  cleanup_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove local build files
        run: |
          rm -rf dist/
          rm -rf build_*/
          rm -rf build-*/
          rm -f *.spec

  delete_artifacts:
    if: ${{ inputs.delete_github_artifacts }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete GitHub Artifacts
        uses: actions/github-script@v8
        env:
          PREFIX: ${{ inputs.artifact_prefix }}
        with:
          script: |
            const prefix = process.env.PREFIX;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const artifacts = await github.paginate(github.rest.actions.listArtifactsForRepo, { owner, repo, per_page: 100 });
            if (artifacts.length === 0) {
              console.log("No artifacts found");
            }
            for (const artifact of artifacts) {
              if (artifact.name.includes(prefix)) {
                console.log(`Deleting artifact: ${artifact.name}`);
                await github.rest.actions.deleteArtifact({ owner, repo, artifact_id: artifact.id });
              }
            }
